{{-- filepath: resources/views/emails/welcome-new-user-text.blade.php --}}
Welcome to {{ $companyName }}!

Hello {{ $user->name }},

We're thrilled to welcome you to Virtopus Agency! Your account has been successfully created and you're now part of our growing community of talented professionals.

=== YOUR LOGIN CREDENTIALS ===
Email: {{ $user->email }}
Temporary Password: {{ $temporaryPassword }}
Role: {{ ucfirst($user->role) }}

⚠️ IMPORTANT SECURITY NOTICE ⚠️
This is a temporary password generated by our system. For your security, please log in and change your password immediately after your first login.

🔗 ACCESS YOUR ACCOUNT
{{ $loginUrl }}

🚀 WHAT'S NEXT?
✓ Log in to your account using the credentials above
✓ Change your password in the account settings
✓ Complete your profile information
@if($user->role === 'client')
✓ Post your first project and find talented freelancers
✓ Explore our freelancer marketplace
✓ Set up your payment preferences
@elseif($user->role === 'freelancer')
✓ Complete your freelancer profile and showcase your skills
✓ Browse available projects that match your expertise
✓ Build your portfolio and set your rates
@elseif($user->role === 'admin')
✓ Access the comprehensive admin dashboard
✓ Manage users, contracts, and platform settings
✓ Monitor platform activity and analytics
@endif

💡 NEED HELP?
Our support team is here to help! If you have any questions or need assistance navigating the platform, contact us at {{ $supportEmail }}.

Best regards,
The {{ $companyName }} Team

---
This email was sent to {{ $user->email }}. If you didn't expect this email, please contact our support team immediately.

{{ $companyName }} | {{ $companyUrl }}
© {{ date('Y') }} {{ $companyName }}. All rights reserved.